# Generated by Django 3.2.4 on 2021-06-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210617_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pswd',
            new_name='lname',
        ),
    ]
