# Generated by Django 3.2.4 on 2021-06-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210618_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('lower_limit', models.CharField(max_length=30)),
                ('upper_limit', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
            ],
        ),
    ]
