# Generated by Django 3.2.4 on 2021-06-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_battery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelTable(
            name='battery',
            table='testconfig',
        ),
    ]
