# Generated by Django 3.2.4 on 2021-06-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210625_1003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='battery',
            table=None,
        ),
    ]
